<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>simpe.wants.plugin</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject />
    <Configurations>Debug;Release;x86</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='x86|AnyCPU'">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='x86|x86'">
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimPE.Filehandlers\SimPE.Filehandlers.csproj" />
    <ProjectReference Include="..\SimPE.Helper\SimPE.Helper.csproj" />
    <ProjectReference Include="..\SimPE.HGBH\SimPE.HGBH.csproj" />
    <ProjectReference Include="..\SimPE.Interfaces\SimPE.Interfaces.csproj" />
    <ProjectReference Include="..\SimPE.Packages\SimPE.Packages.csproj" />
    <ProjectReference Include="..\SimPE.RCOL\SimPE.RCOL.csproj" />
    <ProjectReference Include="..\SimPE.ResourceControls\SimPE.ResourceControls.csproj" />
    <ProjectReference Include="..\SimPE.Scenegraph\SimPE.Scenegraph.csproj" />
    <ProjectReference Include="..\SimPE.Sims\SimPE.Sims.csproj" />
    <ProjectReference Include="..\SimPE.Toolbox\SimPE.Toolbox.csproj" />
    <ProjectReference Include="..\SimPE.WorkSpaceHelper\SimPE.WorkSpaceHelper.csproj" />
    <ProjectReference Include="..\_PJSE\pjse Coder\SimPe pjse coder.csproj" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>
